"""se agrego la sección

Revision ID: 304ffeae2ffb
Revises: e856ff55c7fe
Create Date: 2025-05-27 14:53:28.016794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304ffeae2ffb'
down_revision = 'e856ff55c7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')

    op.drop_table('sections')
    # ### end Alembic commands ###
