"""Añade avatar a users

Revision ID: 567377ce2e39
Revises: 
Create Date: 2025-05-26 14:46:55.075394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567377ce2e39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
