"""Agregue un campo para guardar el nombre del pdf

Revision ID: e856ff55c7fe
Revises: 5613b739b305
Create Date: 2025-05-26 20:49:51.839207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e856ff55c7fe'
down_revision = '5613b739b305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
